//! Implementation of the `lock` subcommand.

use std::collections::HashMap;
use std::collections::HashSet;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;
use std::str::FromStr;
use std::sync::Arc;

use anyhow::Context;
use anyhow::anyhow;
use anyhow::bail;
use clap::Parser;
use colored::Colorize;
use crankshaft::docker::Docker;
use indicatif::ProgressStyle;
use reqwest::Client;
use reqwest::StatusCode;
use serde::Deserialize;
use serde::Serialize;
use tracing::Level;
use tracing::span;
use tracing::warn;
use tracing_indicatif::span_ext::IndicatifSpanExt;
use wdl::analysis::Diagnostics;
use wdl::ast::AstNode;
use wdl::ast::AstToken;
use wdl::ast::Diagnostic;
use wdl::ast::Severity;
use wdl::ast::Span;
use wdl::ast::SupportedVersion;
use wdl::ast::v1::Expr;
use wdl::ast::v1::LiteralExpr;
use wdl::ast::v1::LiteralString;
use wdl::ast::v1::RequirementsItem;
use wdl::ast::v1::RuntimeItem;
use wdl::ast::v1::TaskDefinition;
use wdl::ast::version::V1;
use wdl::diagnostics::DiagnosticCounts;
use wdl::diagnostics::Mode;
use wdl::diagnostics::emit_diagnostics;
use wdl::engine::v1::ContainerSource;
use wdl::engine::v1::ImageDigests;
use wdl::engine::v1::ImageOverrideMap;

use crate::Config;
use crate::analysis::Analysis;
use crate::analysis::Source;
use crate::commands::CommandError;
use crate::commands::CommandResult;

/// Name for the lock file.
pub(crate) const LOCK_FILE: &str = "sprocket.lock";

/// Warning header for the lockfile.
const FILE_HEADER: &str = r#"# This file is automatically generated by `sprocket lock`.
# It is not intended for manual editing.
"#;

/// Arguments for the `lock` subcommand.
#[derive(Parser, Debug)]
pub struct Args {
    /// A source WDL document, directory, or URL.
    #[clap(value_name = "SOURCE")]
    pub source: Option<Source>,

    /// Output directory for the lock file.
    #[clap(short, long, value_name = "DIR")]
    pub output: Option<PathBuf>,

    /// The report mode.
    #[arg(short = 'm', long, value_name = "MODE")]
    pub report_mode: Option<Mode>,
}

/// Represents the lock file structure.
#[derive(Debug, Default, Serialize, Deserialize)]
pub(crate) struct LockFile {
    /// See [`ImageOverrideMap`].
    pub images: Arc<ImageOverrideMap>,
}

impl LockFile {
    /// Attempt to read a `LockFile` from the given `path`.
    ///
    /// Returns `Ok(None)` if the path does not exist.
    pub(crate) fn load(path: impl AsRef<Path>) -> anyhow::Result<Option<Self>> {
        let path = path.as_ref();
        let lock_file = match std::fs::read_to_string(path) {
            Ok(lock_file) => lock_file,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => bail!("failed to read `{}`: {e}", path.display()),
        };

        toml::from_str::<Self>(&lock_file)
            .context("failed to parse lock file")
            .map(Some)
    }
}

/// Create a "no container specified" diagnostic.
fn no_container(span: Span, version: SupportedVersion) -> Diagnostic {
    let section_name = if version >= SupportedVersion::V1(V1::Two) {
        "requirements"
    } else {
        "runtime"
    };

    Diagnostic::note("no container specified")
        .with_highlight(span)
        .with_help(format!("consider adding a `{section_name}` section"))
}

/// Create a "container with placeholder" diagnostic.
fn container_with_placeholder(span: Span) -> Diagnostic {
    Diagnostic::warning("container with placeholder")
        .with_highlight(span)
        .with_help("lock entries cannot be generated for placeholder values")
}

/// Create an "unknown container source" diagnostic.
fn unknown_source(span: Span) -> Diagnostic {
    Diagnostic::note("unknown container source")
        .with_label("this will not be included in the lockfile", span)
}

/// Determine the container images that the `task` references.
fn task_container_images(
    task: TaskDefinition,
    version: SupportedVersion,
) -> (Vec<ContainerSource>, Diagnostics) {
    fn check_string(
        expr: &Expr,
        s: &LiteralString,
        containers: &mut Vec<ContainerSource>,
        diagnostics: &mut Diagnostics,
    ) {
        match s.text() {
            Some(text) => {
                let mut container = String::new();
                text.unescape_to(&mut container);

                let source = ContainerSource::from_str(&container).expect("infallible");
                match source {
                    // Already technically locked, would require a manual override.
                    ContainerSource::SifFile(_) => {}
                    ContainerSource::Unknown(_) => {
                        diagnostics.add(unknown_source(expr.span()));
                    }
                    ContainerSource::Docker(ref image) | ContainerSource::Oras(ref image) => {
                        if image.contains("@sha256:") {
                            // Nothing to do, already locked
                            return;
                        }

                        containers.push(source);
                    }
                    ContainerSource::Library(ref image) => {
                        if image.contains(":sha256.") {
                            // Nothing to do, already locked
                            return;
                        }

                        containers.push(source);
                    }
                }
            }
            None => {
                diagnostics.add(container_with_placeholder(expr.span()));
            }
        }
    }

    let expr = match task.requirements() {
        Some(requirements) => requirements
            .container()
            .and_then(|c| RequirementsItem::cast(c.inner().clone()))
            .map(|r| r.expr()),
        None => task
            .runtime()
            .and_then(|r| r.container())
            .and_then(|c| RuntimeItem::cast(c.inner().clone()))
            .map(|r| r.expr()),
    };

    let mut containers = Vec::new();
    let mut diagnostics = Diagnostics::default();
    let Some(expr) = expr else {
        diagnostics.add(no_container(task.name().span(), version));
        return (containers, diagnostics);
    };

    match expr {
        Expr::Literal(LiteralExpr::String(ref s)) => {
            check_string(&expr, s, &mut containers, &mut diagnostics);
        }
        Expr::Literal(LiteralExpr::Array(arr)) => {
            for e in arr.elements() {
                let Expr::Literal(LiteralExpr::String(s)) = &e else {
                    unreachable!("should be handled by validation");
                };

                check_string(&e, s, &mut containers, &mut diagnostics);
            }
        }
        _ => {
            diagnostics.add(container_with_placeholder(expr.span()));
            return (containers, diagnostics);
        }
    }

    (containers, diagnostics)
}

/// Context used for registry image inspection.
struct RegistryContext {
    /// Handle to the Docker client.
    docker: Docker,
    /// The `oras` binary path, if needed.
    oras_path: Option<PathBuf>,
    /// An HTTP client, if needed.
    client: Option<Client>,
}

impl RegistryContext {
    /// Create a new `RegistryContext`
    ///
    /// Depending on the `images` referenced, this may search the system for
    /// certain binaries.
    fn init(images: &HashSet<ContainerSource>) -> anyhow::Result<RegistryContext> {
        let docker = Docker::with_defaults().context("failed to connect to Docker daemon")?;

        let mut oras_expected = false;
        let mut singularity_expected = false;
        for image in images {
            match image {
                ContainerSource::Docker(_) => {}
                ContainerSource::Library(_) => singularity_expected = true,
                ContainerSource::Oras(_) => oras_expected = true,
                ContainerSource::SifFile(_) => {}
                ContainerSource::Unknown(_) => {}
            }
        }

        let mut oras_path = None;
        if oras_expected {
            oras_path = Some(which::which("oras").context("failed to find `oras` binary")?);
        }

        let mut client = None;
        if singularity_expected {
            client = Some(Client::new());
        }

        Ok(RegistryContext {
            docker,
            oras_path,
            client,
        })
    }

    /// Determine the docker OCI index digest for the given `image`.
    async fn determine_docker_digest(&self, image: &str) -> anyhow::Result<String> {
        match self
            .docker
            .inner()
            .inspect_registry_image(image, None)
            .await
        {
            Ok(inspect) => Ok(inspect.descriptor.digest.expect("should have a digest")),
            Err(bollard::errors::Error::DockerResponseServerError {
                status_code: 404, ..
            }) => {
                bail!("image `{image}` not found")
            }
            Err(e) => Err(e).context("inspecting registry image"),
        }
    }

    /// Determine the OCI index digest for the given `image`.
    fn determine_oras_digest(&self, image: &str) -> anyhow::Result<String> {
        let output = Command::new(self.oras_path.as_ref().unwrap())
            .arg("resolve")
            .arg(image)
            .output()
            .context("failed to run `oras resolve`")?;
        if !output.status.success() {
            eprintln!("{}", String::from_utf8_lossy(&output.stderr));
            bail!("failed to resolve image `{image}`");
        }

        let digest = String::from_utf8_lossy(&output.stdout);
        if !digest.starts_with("sha256") {
            bail!("unexpected output from `oras resolve`: {digest}");
        }

        Ok(digest.trim().to_string())
    }

    /// Determine the architecture-specific digests for a Sylabs Cloud image.
    pub async fn determine_sylabs_digests(
        &self,
        image: &str,
        tag: &str,
    ) -> anyhow::Result<HashMap<String, ContainerSource>> {
        /// Mapping of Sylabs architecture variants ->
        /// [`std::env::consts::ARCH`] variants.
        const SUPPORTED_ARCHITECTURES: &[(&str, &str)] = &[
            ("amd64", "x86_64"),
            ("arm64", "aarch64"),
            ("arm", "arm"),
            ("ppc64le", "ppc64le"),
            ("s390x", "s390x"),
            ("386", "x86"),
        ];

        #[derive(Deserialize)]
        struct Response {
            data: Data,
        }

        #[derive(Deserialize)]
        struct Data {
            hash: String,
        }

        // library://library.sylabs.io/library/default/ubuntu:latest
        //           ----------------- ------- ------- -------------
        //                   |            |       |          |
        //                registry      entity collection   image

        let mut parts = image.split('/').collect::<Vec<_>>();

        let registry = if !parts.is_empty() && (parts[0].contains('.') || parts[0].contains(':')) {
            parts.remove(0)
        } else {
            "library.sylabs.io"
        };

        let (entity, collection, container) = match parts.len() {
            // library://ubuntu:latest
            1 => ("library", "default", String::from(parts[0])),
            // library://library/default/ubuntu:latest
            3 => (parts[0], parts[1], String::from(parts[2])),
            _ => bail!("invalid image format"),
        };

        let client = self.client.as_ref().unwrap();
        let mut resolved_digests = HashMap::new();

        for (arch, normalized_arch) in SUPPORTED_ARCHITECTURES {
            let url = format!(
                "https://{registry}/v1/images/{entity}/{collection}/{container}:{tag}?arch={arch}",
            );

            let request = client.get(&url).build()?;
            let response = client.execute(request).await?;

            match response.status() {
                StatusCode::OK => {
                    let response = response
                        .json::<Response>()
                        .await
                        .context("failed to parse response")?;
                    resolved_digests.insert(
                        normalized_arch.to_string(),
                        ContainerSource::Library(format!("{image}:{}", response.data.hash)),
                    );
                }
                // Assume this means the specified arch isn't supported
                StatusCode::NOT_FOUND => {}
                _ => {
                    bail!("failed to inspect image `{image}:{tag}` for arch `{arch}`");
                }
            }
        }

        if resolved_digests.is_empty() {
            bail!("`{image}:{tag}` was not found for any architecture on `{registry}`");
        }

        Ok(resolved_digests)
    }
}

/// Performs the `lock` command.
pub async fn lock(args: Args, config: Config, colorize: bool) -> CommandResult<()> {
    let output_path = args
        .output
        .unwrap_or_else(|| PathBuf::from(std::path::Component::CurDir.as_os_str()))
        .join(LOCK_FILE);

    let s = args.source.unwrap_or_default();
    let results = Analysis::default()
        .add_source(s)
        .fallback_version(config.common.wdl.fallback_version.inner().cloned())
        .run()
        .await
        .map_err(CommandError::from)?;

    let mut counts = DiagnosticCounts::default();
    let mut images: HashSet<ContainerSource> = HashSet::new();
    for result in results {
        let path = result.document().path().to_string();
        let source = result.document().root().text().to_string();

        emit_diagnostics(
            &path,
            source,
            result.document().diagnostics().filter(|d| {
                if d.severity() == Severity::Error {
                    counts.errors += 1;
                    return true;
                }

                false
            }),
            args.report_mode.unwrap_or_default(),
            colorize,
        )
        .context("failed to emit diagnostics")?;

        let doc = result.document();

        for task in doc
            .root()
            .ast_with_version_fallback(result.document().config().fallback_version())
            .as_v1()
            .expect("should be a v1 document")
            .tasks()
        {
            let (sources, diagnostics) = task_container_images(task, doc.version().unwrap());
            emit_diagnostics(
                &doc.path(),
                doc.root().text().to_string(),
                diagnostics.iter(),
                args.report_mode.unwrap_or_default(),
                colorize,
            )?;

            images.extend(sources);
        }
    }

    if let Some(e) = counts.verify_no_errors() {
        return Err(e.into());
    }

    let mut map: ImageOverrideMap = HashMap::new();
    let context = RegistryContext::init(&images)?;

    let template = if colorize {
        "[{elapsed_precise:.cyan/blue}] {spinner:.cyan/blue} checking image {msg} ({pos}/{len})"
    } else {
        "[{elapsed_precise}] {spinner} checking image {msg} ({pos}/{len})"
    };

    let progress_bar = span!(Level::WARN, "progress");
    progress_bar.pb_set_style(&ProgressStyle::with_template(template).unwrap());
    progress_bar.pb_set_length(images.len().try_into().unwrap());
    progress_bar.pb_start();

    for (index, source) in images.iter().enumerate() {
        let source_str = format!("{source:#}");

        progress_bar.pb_set_position(index.saturating_add(1).try_into().unwrap());
        progress_bar.pb_set_message(&source_str.magenta());

        match source {
            ContainerSource::Docker(image) => {
                let prefix = image.split(':').next().unwrap_or("");
                let digest = context.determine_docker_digest(image).await?;

                map.insert(
                    image.clone(),
                    ImageDigests::OciManifest(ContainerSource::Docker(format!(
                        "{prefix}@{digest}"
                    ))),
                );
            }
            ContainerSource::Library(image) => {
                let Some((image, tag)) = image.rsplit_once(':') else {
                    return Err(anyhow!("image doesn't specify a tag").into());
                };

                let digests = context.determine_sylabs_digests(image, tag).await?;

                map.insert(source_str, ImageDigests::PerArch(digests));
            }
            ContainerSource::Oras(image) => {
                let prefix = image.split(':').next().unwrap_or("");
                let digest = context.determine_oras_digest(image)?;
                map.insert(
                    source_str,
                    ImageDigests::OciManifest(ContainerSource::Oras(format!("{prefix}@{digest}"))),
                );
            }
            ContainerSource::SifFile(_) | ContainerSource::Unknown(_) => {
                unreachable!("should be filtered out before")
            }
        }
    }

    if map.is_empty() {
        warn!("no applicable images were found");
        return Ok(());
    }

    let lock = LockFile {
        images: Arc::new(map),
    };
    let data = toml::to_string_pretty(&lock).context("failed to serialize lock contents")?;
    write_lock_file(&output_path, data).context("failed to create lock file")?;

    Ok(())
}

/// Write the lockfile to disk.
fn write_lock_file(path: &Path, data: String) -> anyhow::Result<()> {
    let mut f = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)?;
    f.write_all(FILE_HEADER.as_bytes())?;
    f.write_all(data.as_bytes())?;
    Ok(())
}
